@startuml Model Package Class Diagram

top to bottom direction

rectangle "Essentials and less complex"{

    class "Income"{
        {field} - name : String
        {field} - fixed : Boolean
        {field} - value : Double

        {method} + void set_name
        {method} + void set_fixed_status
        {method} + void set_value
    }

    class "Expense"{
        {field} -name : String
        {field} -fixed : Boolean
        {field} -value : Double

        {method} +void set_name
        {method} +void set_fixed_status
        {method} +void set_value
    }
    
    class "Month"{
        {field} - incomes : ArrayList<Income>
        {field} - expenses : ArrayList<Expense>
        {field} - balance : Double
        {method} + void add_income()
        {method} + void rmv_income()
        {method} + void add_expense()
        {method} + void rmv_expense()
    }

    note bottom of "Month"
        The methods related to incomes 
        and expenses in the "Month" Class
        only concerns its own incomes and
        expenses.

        Though its worth mentioning that
        the action of add/rmv FIXED
        income/expense affects other months, thus
        is a "bigger" action that EVENTUALLY
        leads to the calling of the said methods.
    end note 
}

rectangle "More complex"{
    class "Credit Card"{
        {field} name : String
        {field} purchases : ArrayList<Purchase>
    }

    class "Purchase"{
        {field} name : String
        {field} total_price : Double
        {field} number_of_installments : Int
    }

    note bottom of "Purchase"
        The Purchase class represents
        credit cards purchases.
        It authomatically calculates 
        each installment value based on
        the product value and number of
        installments.
        It won't support installments
        with interest (not yet).
    end note 
}


@enduml