@startuml System Use Cases 

skinparam actorStyle awesome
left to right direction

:System: 

package "Main Use Cases"{
    usecase (Calculate final balance) as UC1
    usecase (Calculate credid card invoice) as UC2
    usecase (Save fixed incomes/expenses and apply them into every months planner) as UC3
}

System --> UC1
System --> UC2
System --> UC3

@enduml