@startuml User Use Cases

skinparam actorStyle awesome
left to right direction

:User: 

package "Main Use Cases" as MUC{
    usecase (Register fixed income) as UC1
    usecase (Register variable income) as UC2
    usecase (Register fixed expenses) as UC3
    usecase (Register variable expenses) as UC4
    usecase (Register credit cards) as UC5
    usecase (Register credit cards purchases) as UC6
}

note right of MUC
    The main use cases are the ones
    that the application must have
end note

User --> UC1
User --> UC2
User --> UC3
User --> UC4
User --> UC5
User --> UC6

package "Secondary Use Cases" as SUC{
    usecase (Register goals) as UC1_SEC
    usecase (Register goals investments) as UC2_SEC
}

note right of SUC
    The secondary use cases are the ones
    that may be implemented later on
end note

User --> UC1_SEC
User --> UC2_SEC

@enduml